stages:
  - test
  - build
  - run

lint:
  stage: test
  image: golangci/golangci-lint:v1.41.1
  script:
    - golangci-lint run -v -E gofmt -E goconst -E gocritic -E gocognit -E gocyclo
  except:
    - schedules

binary:
  stage: build
  image: golang:1.17-buster
  script: go build
  except:
    - schedules

check-availability:
  stage: run
  image: golang:1.17-buster
  before_script:
    - go build
  script:
    - ./cineplex_ticket_checker -t $THEATRE_IDS -w $WEBHOOK_URL $MOVIES
  only:
    - schedules
